#!/bin/bash

set -e
#sudo apt-get update || apt-get install bc
#apt-get install bc >/dev/null 2>&1
if [ "$1" = "" ]
  then
    printf "Warning: No arguments supplied\n"
    exit
fi

HOME=~/lyft-perception-challenge/workspace
VIDEO="$HOME/Example/test_video.mp4"
# Set frames constant for test video
FRAMES=30.0

# Space for new command
SPACE=' '

# Make run command
RUN_CMD=$1$SPACE$VIDEO
echo $RUN_CMD

# Set clock
start_time=$(date +'%s')

# Run suppiled function with image argument
# Outputs pixel labeled array
# Stored for comparison
$RUN_CMD > $HOME/Example/tester_data

# Output runtime
end_time=$(date +'%s')

printf "\nYour program has been ran, now grading...\n"

FPS=$(echo "scale=3; $FRAMES/($end_time - $start_time)" | bc)

CODE_CMD="python $HOME/Example/paper_score"
TMP_LOCATION="$HOME/Example/tester_data"

PYTHON_CMD=$CODE_CMD$SPACE$TMP_LOCATION$SPACE$FPS$SPACE$input_user
echo $PYTHON_CMD
# Run python program to calculate accuracy and store info for database
ACC=$($PYTHON_CMD)

printf "\nYour program runs at $FPS FPS\n\n"
echo $ACC
echo ' '

rm $HOME/Example/tester_data
rm $HOME/Example/image.png
